"""alteracao tabela patente

Revision ID: d394d453d223
Revises: d879b06b0c0d
Create Date: 2026-05-06 20:28:22.965577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd394d453d223'
down_revision: Union[str, Sequence[str], None] = 'd879b06b0c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patente', sa.Column('nivel_minimo', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.drop_column('patente', 'xp_minimo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patente', sa.Column('xp_minimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('patente', 'nivel_minimo')
    # ### end Alembic commands ###
