"""cascade conquista

Revision ID: c4c211480a11
Revises: e739ff09be1c
Create Date: 2026-05-17 19:36:01.084576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c211480a11'
down_revision: Union[str, Sequence[str], None] = 'e739ff09be1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuario_conquista_conquista_id_fkey'), 'usuario_conquista', type_='foreignkey')
    op.drop_constraint(op.f('usuario_conquista_usuario_id_fkey'), 'usuario_conquista', type_='foreignkey')
    op.create_foreign_key('usuario_conquista_usuario_id_fkey', 'usuario_conquista', 'usuario', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')
    op.create_foreign_key('usuario_conquista_conquista_id_fkey', 'usuario_conquista', 'conquista', ['conquista_id'], ['id_conquista'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuario_conquista_usuario_id_fkey', 'usuario_conquista', type_='foreignkey')
    op.drop_constraint('usuario_conquista_conquista_id_fkey', 'usuario_conquista', type_='foreignkey')
    op.create_foreign_key(op.f('usuario_conquista_usuario_id_fkey'), 'usuario_conquista', 'usuario', ['usuario_id'], ['id_usuario'])
    op.create_foreign_key(op.f('usuario_conquista_conquista_id_fkey'), 'usuario_conquista', 'conquista', ['conquista_id'], ['id_conquista'])
    # ### end Alembic commands ###
