"""Nivel Deletado

Revision ID: e739ff09be1c
Revises: d394d453d223
Create Date: 2026-05-16 18:02:04.986884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e739ff09be1c'
down_revision: Union[str, Sequence[str], None] = 'd394d453d223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patente', sa.Column('xp_minimo', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('patente', 'nivel_minimo')
    op.drop_constraint(op.f('usuario_nivel_id_fkey'), 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'nivel_id')
    op.drop_table('nivel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nivel_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('usuario_nivel_id_fkey'), 'usuario', 'nivel', ['nivel_id'], ['id_nivel'])
    op.add_column('patente', sa.Column('nivel_minimo', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_column('patente', 'xp_minimo')
    op.create_table('nivel',
    sa.Column('id_nivel', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('xp_minimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_nivel', name=op.f('nivel_pkey'))
    )
    # ### end Alembic commands ###
