"""relacao entre usuario e nivel

Revision ID: d879b06b0c0d
Revises: 082bb6f593ee
Create Date: 2026-05-06 20:16:46.574400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd879b06b0c0d'
down_revision: Union[str, Sequence[str], None] = '082bb6f593ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nivel_id', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.create_foreign_key(None, 'usuario', 'nivel', ['nivel_id'], ['id_nivel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'nivel_id')
    # ### end Alembic commands ###
