"""tabela nivel

Revision ID: 082bb6f593ee
Revises: 156255b7da4c
Create Date: 2026-05-06 20:08:37.721995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082bb6f593ee'
down_revision: Union[str, Sequence[str], None] = '156255b7da4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nivel',
    sa.Column('id_nivel', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('xp_minimo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_nivel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nivel')
    # ### end Alembic commands ###
